program: net_sweep_train_80_20_split.py
project: ESKD_SWEEP_PARAMS_VAL_CORRECTED
# Qua devo mettere grid come method se no se metto bayes non fa una vera cross fold ma include il fold come se fosse una metrica da ottimizzare
method: grid
metric:
  name: train/f1-score
  goal: maximize

parameters:
  fold:
    values: [1,2,3,4,5]  # qui definisci i fold
  learning_rate: 
    values: [0.000001, 0.0001, 0.001, 0.01, 0.1, 0.2]
  dropout:
    values: [0.1, 0.2, 0.3, 0.5]
  batch_size:
    values: [16, 32, 64]
  optimizer:
    values: ["adam", "sgd"]

